### ISSUE TITLE
sliders sizing messed up under some circumstances

### ISSUE THREAD

**Issue by mrRay** [Vidvox/oscqueryhtml#61]
screenshot attached- reproducible using the sample document (also attached)
[SampleDocument.json.zip](https://github.com/Vidvox/oscqueryhtml/files/2442965/SampleDocument.json.zip)
<img width="1228" alt="screen shot 2018-10-03 at 1 02 35 pm" src="https://user-images.githubusercontent.com/27467/46426511-cbf27680-c70c-11e8-855f-eb73ecc8e63b.png">

**Comment by dustmop** [comment]
Embarrassing typo, totally my fault. Fixed with ca25041.
